plugins {
    id 'com.android.library'
    id "com.vanniktech.maven.publish" version "0.34.0"
}

android {
    namespace "tv.danmaku.ijk.media.player_arm64"
    // http://tools.android.com/tech-docs/new-build-system/user-guide/build-variants
    // http://tools.android.com/tech-docs/new-build-system/tips
    //noinspection GroovyAssignabilityCheck
    compileSdkVersion rootProject.ext.compileSdkVersion
    //noinspection GroovyAssignabilityCheck
    buildToolsVersion rootProject.ext.buildToolsVersion

    ndkVersion "26.3.11579264"

    defaultConfig {
        minSdkVersion 9
        targetSdkVersion rootProject.ext.targetSdkVersion
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets.main {
        jniLibs.srcDirs 'src/main/libs'
        jni.srcDirs = [] // This prevents the auto generation of Android.mk
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

apply from: new File(rootProject.projectDir, "tools/gradle-on-demand.gradle");

def libVersion = rootProject.ext.sdk.version
ext.isReleaseVersion = !libVersion.endsWith("SNAPSHOT")
mavenPublishing {

    coordinates("com.tencent.iot.thirdparty.android", "ijkplayer-arm64", libVersion)
    publishToMavenCentral()
    signAllPublications()

    pom {
        name = 'ijkplayer'
        description = 'Tencent Link Android library'
        url = 'https://github.com/tencentyun/iot-ijkplayer'
        licenses {
            license {
                name = 'Tencent Binary License'
                url = 'https://github.com/tencentyun/iot-link-android/blob/master/explorer-link-android/LICENSE'
            }
        }
        developers {
            developer {
                id = 'tencent_archurtan'
                name = 'Tencent archurtan'
                email = 'archurtan@tencent.com'
            }
        }
        scm {
            url = 'scm:git@github.com:tencentyun/iot-ijkplayer.git'
            connection = 'scm:git@github.com:tencentyun/iot-ijkplayer.git'
            developerConnection = 'scm:git@github.com:tencentyun/iot-ijkplayer.git'
        }
    }
}