name: IOT IJK ANDROID DEBUG CI

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches: [ master ]

env:
  IOT_SONATYPE_USERNAME: ${{ secrets.IOT_SONATYPE_USERNAME }}
  IOT_SONATYPE_PASSWORD: ${{ secrets.IOT_SONATYPE_PASSWORD }}
  GPG_DECRYPT_PASSPHRASE: ${{ secrets.GPG_DECRYPT_PASSPHRASE }}

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download r10e NDK
        run: |
          wget https://dl.google.com/android/repository/android-ndk-r10e-darwin-x86_64.zip
          unzip android-ndk-r10e-darwin-x86_64.zip
      - name: Update SDK Version
        run: bash .github/script/updateVersionForSnapshot.sh
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
      - name: Build with Gradle
        run: |
          ls -l /Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r10e
          perl -i -pe "s#.*HOST_ARCH=x86_64.*#\t\tx86_64|amd64|arm64) HOST_ARCH=x86_64;;#g" /Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r10e/ndk-build
          export ANDROID_NDK=/Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r10e
          export ANDROID_NDK_ROOT=/Users/runner/work/iot-ijkplayer/iot-ijkplayer/android-ndk-r10e

          sh .github/script/build_armv7a.sh
          cd android/ijkplayer
          ./gradlew :ijkplayer-armv7a:assemble
          ./gradlew :ijkplayer-arm64:assemble
          ./gradlew :ijkplayer-java:assemble

      - name: Upload AARs
        uses: actions/upload-artifact@v4
        with:
          name: aars
          path: |
            /Users/runner/work/iot-ijkplayer/iot-ijkplayer/android/ijkplayer/ijkplayer-armv7a/build/outputs/aar/ijkplayer-armv7a-debug.aar
            /Users/runner/work/iot-ijkplayer/iot-ijkplayer/android/ijkplayer/ijkplayer-arm64/build/outputs/aar/ijkplayer-arm64-debug.aar
            /Users/runner/work/iot-ijkplayer/iot-ijkplayer/android/ijkplayer/ijkplayer-java/build/outputs/aar/ijkplayer-java-debug.aar

      - name: Publish aar to Maven
        run: |
          cd android/ijkplayer
          ./gradlew :ijkplayer-armv7a:publishToMavenCentral
          ./gradlew :ijkplayer-arm64:publishToMavenCentral
          ./gradlew :ijkplayer-java:publishToMavenCentral
